# Generated by Django 5.0 on 2024-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='desc',
            field=models.TextField(default='hello'),
        ),
    ]
